[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "autoammonia"
version = "0.1.0"
description = "A package for ammonia SDL automation."
authors = [
    { name = "Your Name", email = "your.email@example.com" }
]
readme = "readme.md"
requires-python = ">=3.8"
dynamic = ["dependencies"]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
autoammonia_deploy_dynamic = "autoammonia.prefect.dynamic_deploy:main"
autoammonia_run_dynamic = "autoammonia.prefect.dynamic_trigger:main"
autoammonia_flow_off_dynamic = "autoammonia.prefect.dynamic_flows_shutdown:main"
autoammonia_deploy_reaction = "autoammonia.prefect.static_deploy_reaction:main"
autoammonia_deploy_analysis = "autoammonia.prefect.static_deploy_analysis:main"
autoammonia_run = "autoammonia.prefect.static_trigger:trigger_deployments"
autoammonia_rx_test = "autoammonia.testing.rx_module_test:main"
autoammonia_hardware_test = "autoammonia.testing.hardware_test:main"
autoammonia_exp_requester = "autoammonia.experiment_queue:request_experiments"
autoammonia_db_create_tables = "autoammonia.db.create_tables:main"
autoammonia_db_test = "autoammonia.db.test_db_connection:main"
autoammonia_db_drop_tables = "autoammonia.db.drop_tables:main"
