[longerWE01]
class = "matterlab_pumps.LongerPeristalticPump"
com_port = "COM10"
address = 1
baudrate = 1200

[longerCE01]
class = "matterlab_pumps.LongerPeristalticPump"
com_port = "COM10"
address = 2
baudrate = 1200

[tecanRX01]
class = "matterlab_pumps.RunzePump"
com_port = "COM3"
address = 3
syringe_volume = 0.0048
num_valve_port = 12

[tecanAZ01]
class = "matterlab_pumps.RunzePump"
com_port = "COM20"
address = 1
syringe_volume = 0.0011
num_valve_port = 12

[valveRX01]
class = "matterlab_valves.RunzeSelectionValve"
com_port = "COM19"
address = 2
num_port = 12

[valveAZ01]
class = "matterlab_valves.RunzeSelectionValve"
com_port = "COM18"
address = 1
num_port = 12

[potentiostat01]
class = "pyBEEP.PotentiostatController"
device_class = "pyBEEP.PotentiostatDevice"
device_kwargs = { port = "COM15", address = 1 }

[UVVIS01]
class = "matterlab_spectrometers.HamamatsuMiniSpectrometer"
product_id = "J4251028"
calibration_coefficient = [1.598749839E+002, 3.004208898E-001, 1.943984946E-005, 1.156674313E-009, -1.539714024E-012, 2.014714535E-016]

[lamp01]
class = "autoammonia.hardware.uv_vis_lamp.PulsedLamp"
device_class = "autoammonia.hardware.uv_vis_lamp.Arduino"
device_kwargs = { port = "COM16" }
pulse_interval = 0.05

